#pragma once

enum GpuObjectType {
    GPU_OBJECT_AXON = 0,
    GPU_OBJECT_GLIAL_SOMA = 1,
    GPU_OBJECT_GLIAL_PROCESS = 2,
    GPU_OBJECT_ARTERY = 3,
    GPU_OBJECT_VEIN = 4,
    GPU_OBJECT_CAPILLARY = 5    
};